# Generated by Django 2.1.5 on 2020-07-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_data',
            new_name='birth_date',
        ),
    ]
